"""baseline

Revision ID: 8d582a570e8d
Revises:
Create Date: 2026-04-19 17:43:01.244856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8d582a570e8d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_type", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversations_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_conversations_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_owner_type"), ["owner_type"], unique=False
        )

    op.create_table(
        "entity_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("caption", sa.String(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("entity_images", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_entity_images_id"), ["id"], unique=False)
        batch_op.create_index(
            "ix_entity_images_lookup",
            ["entity_type", "entity_id", "display_order"],
            unique=False,
        )

    op.create_table(
        "golf_resorts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_norm", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("source_urls", sa.Text(), nullable=False),
        sa.Column("country_code", sa.String(), nullable=False),
        sa.Column("region_name_raw", sa.String(), nullable=True),
        sa.Column("vacationmap_region_key", sa.String(), nullable=True),
        sa.Column("town", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("hotel_name", sa.String(), nullable=True),
        sa.Column("hotel_type", sa.String(), nullable=True),
        sa.Column("star_rating", sa.Integer(), nullable=True),
        sa.Column("price_category", sa.String(), nullable=True),
        sa.Column("best_months", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amenities", sa.Text(), nullable=False),
        sa.Column("rank_rating", sa.Integer(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=False),
        sa.Column("personal_notes", sa.Text(), nullable=True),
        sa.Column("source_checked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("golf_resorts", schema=None) as batch_op:
        batch_op.create_index("ix_golf_resorts_country", ["country_code"], unique=False)
        batch_op.create_index(batch_op.f("ix_golf_resorts_id"), ["id"], unique=False)
        batch_op.create_index(
            "ix_golf_resorts_name_norm_country",
            ["name_norm", "country_code"],
            unique=False,
        )
        batch_op.create_index(
            "ix_golf_resorts_vm_region_key", ["vacationmap_region_key"], unique=False
        )

    op.create_table(
        "trip_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("target_month", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("activity_weights", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trip_plans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trip_plans_id"), ["id"], unique=False)

    op.create_table(
        "year_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("activity_weights", sa.Text(), nullable=False),
        sa.Column("windows", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("year_plans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_year_plans_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_year_plans_year"), ["year"], unique=False)

    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=True),
        sa.Column("trip_id", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trip_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_messages_id"), ["id"], unique=False
        )

    op.create_table(
        "excluded_destinations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("region_lookup_key", sa.String(), nullable=True),
        sa.Column("destination_name", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("ai_reasoning", sa.Text(), nullable=True),
        sa.Column("user_note", sa.String(), nullable=True),
        sa.Column("excluded_at", sa.DateTime(), nullable=False),
        sa.Column("resort_id", sa.Integer(), nullable=True),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["trip_id"], ["trip_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("excluded_destinations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_excluded_destinations_id"), ["id"], unique=False
        )

    op.create_table(
        "golf_courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resort_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_norm", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("source_urls", sa.Text(), nullable=False),
        sa.Column("country_code", sa.String(), nullable=True),
        sa.Column("region_name_raw", sa.String(), nullable=True),
        sa.Column("vacationmap_region_key", sa.String(), nullable=True),
        sa.Column("town", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("holes", sa.Integer(), nullable=True),
        sa.Column("par", sa.Integer(), nullable=True),
        sa.Column("length_yards", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("architect", sa.String(), nullable=True),
        sa.Column("year_opened", sa.Integer(), nullable=True),
        sa.Column("difficulty", sa.Integer(), nullable=True),
        sa.Column("signature_holes", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("green_fee_low_eur", sa.Integer(), nullable=True),
        sa.Column("green_fee_high_eur", sa.Integer(), nullable=True),
        sa.Column("green_fee_notes", sa.String(), nullable=True),
        sa.Column("best_months", sa.Text(), nullable=False),
        sa.Column("rank_rating", sa.Integer(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=False),
        sa.Column("personal_notes", sa.Text(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("source_checked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resort_id"], ["golf_resorts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("golf_courses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_golf_courses_id"), ["id"], unique=False)
        batch_op.create_index(
            "ix_golf_courses_name_norm_country",
            ["name_norm", "country_code"],
            unique=False,
        )
        batch_op.create_index("ix_golf_courses_resort_id", ["resort_id"], unique=False)
        batch_op.create_index("ix_golf_courses_type", ["type"], unique=False)
        batch_op.create_index(
            "ix_golf_courses_vm_region_key", ["vacationmap_region_key"], unique=False
        )

    op.create_table(
        "shortlisted_destinations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("region_lookup_key", sa.String(), nullable=True),
        sa.Column("destination_name", sa.String(), nullable=False),
        sa.Column("ai_reasoning", sa.Text(), nullable=False),
        sa.Column("scores_snapshot", sa.Text(), nullable=True),
        sa.Column("user_note", sa.String(), nullable=True),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column("resort_id", sa.Integer(), nullable=True),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["trip_id"], ["trip_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shortlisted_destinations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_shortlisted_destinations_id"), ["id"], unique=False
        )

    op.create_table(
        "suggested_destinations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("region_lookup_key", sa.String(), nullable=True),
        sa.Column("destination_name", sa.String(), nullable=False),
        sa.Column("ai_reasoning", sa.Text(), nullable=False),
        sa.Column("scores_snapshot", sa.Text(), nullable=True),
        sa.Column("user_note", sa.String(), nullable=True),
        sa.Column("pre_filled_exclude_reason", sa.String(), nullable=True),
        sa.Column("suggested_at", sa.DateTime(), nullable=False),
        sa.Column("resort_id", sa.Integer(), nullable=True),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["trip_id"], ["trip_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("suggested_destinations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_suggested_destinations_id"), ["id"], unique=False
        )

    op.create_table(
        "year_options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year_plan_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("excluded_reason", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["year_plan_id"], ["year_plans.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("year_options", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_year_options_id"), ["id"], unique=False)
        batch_op.create_index("ix_year_options_plan", ["year_plan_id"], unique=False)

    op.create_table(
        "slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year_option_id", sa.Integer(), nullable=False),
        sa.Column("window_index", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("theme", sa.Text(), nullable=False),
        sa.Column("start_year", sa.Integer(), nullable=False),
        sa.Column("start_month", sa.Integer(), nullable=False),
        sa.Column("end_year", sa.Integer(), nullable=False),
        sa.Column("end_month", sa.Integer(), nullable=False),
        sa.Column("exact_start_date", sa.Date(), nullable=True),
        sa.Column("exact_end_date", sa.Date(), nullable=True),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("climate_hint", sa.String(), nullable=True),
        sa.Column("constraints_note", sa.Text(), nullable=True),
        sa.Column("activity_weights", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("excluded_reason", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("trip_plan_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("end_month BETWEEN 1 AND 12", name="ck_slot_end_month"),
        sa.CheckConstraint("start_month BETWEEN 1 AND 12", name="ck_slot_start_month"),
        sa.ForeignKeyConstraint(
            ["trip_plan_id"], ["trip_plans.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["year_option_id"], ["year_options.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("slots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_slots_id"), ["id"], unique=False)
        batch_op.create_index(
            "ix_slots_year_option_window",
            ["year_option_id", "window_index"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("slots", schema=None) as batch_op:
        batch_op.drop_index("ix_slots_year_option_window")
        batch_op.drop_index(batch_op.f("ix_slots_id"))

    op.drop_table("slots")
    with op.batch_alter_table("year_options", schema=None) as batch_op:
        batch_op.drop_index("ix_year_options_plan")
        batch_op.drop_index(batch_op.f("ix_year_options_id"))

    op.drop_table("year_options")
    with op.batch_alter_table("suggested_destinations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_suggested_destinations_id"))

    op.drop_table("suggested_destinations")
    with op.batch_alter_table("shortlisted_destinations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shortlisted_destinations_id"))

    op.drop_table("shortlisted_destinations")
    with op.batch_alter_table("golf_courses", schema=None) as batch_op:
        batch_op.drop_index("ix_golf_courses_vm_region_key")
        batch_op.drop_index("ix_golf_courses_type")
        batch_op.drop_index("ix_golf_courses_resort_id")
        batch_op.drop_index("ix_golf_courses_name_norm_country")
        batch_op.drop_index(batch_op.f("ix_golf_courses_id"))

    op.drop_table("golf_courses")
    with op.batch_alter_table("excluded_destinations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_excluded_destinations_id"))

    op.drop_table("excluded_destinations")
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_messages_id"))

    op.drop_table("conversation_messages")
    with op.batch_alter_table("year_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_year_plans_year"))
        batch_op.drop_index(batch_op.f("ix_year_plans_id"))

    op.drop_table("year_plans")
    with op.batch_alter_table("trip_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trip_plans_id"))

    op.drop_table("trip_plans")
    with op.batch_alter_table("golf_resorts", schema=None) as batch_op:
        batch_op.drop_index("ix_golf_resorts_vm_region_key")
        batch_op.drop_index("ix_golf_resorts_name_norm_country")
        batch_op.drop_index(batch_op.f("ix_golf_resorts_id"))
        batch_op.drop_index("ix_golf_resorts_country")

    op.drop_table("golf_resorts")
    with op.batch_alter_table("entity_images", schema=None) as batch_op:
        batch_op.drop_index("ix_entity_images_lookup")
        batch_op.drop_index(batch_op.f("ix_entity_images_id"))

    op.drop_table("entity_images")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_owner_type"))
        batch_op.drop_index(batch_op.f("ix_conversations_owner_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_id"))

    op.drop_table("conversations")
    # ### end Alembic commands ###
